### ISSUE TITLE
Use release

### ISSUE THREAD

**Issue by heraldofsolace** [eyl327/LaTeX-Gboard-Dictionary#1]
Using a [release](https://docs.github.com/en/github/administering-a-repository/managing-releases-in-a-repository) will help people on mobile to download easily instead of going to the desktop site

**Comment by eyl327** [comment]
Thanks for the advice! I have created a release with the latest version. I had to upload a zip since the default source code zip for the release has a folder containing the files instead of just the files, so it won't import to Gboard.
