### ISSUE TITLE
dictionary.txt disables while importing

### ISSUE THREAD

**Issue by ameybhavsar24** [eyl327/LaTeX-Gboard-Dictionary#3]
When I tried to import the file, the file was disabled (or greyed). How do I resolve this? 
I am using the latest beta of GBoard 9.6.13.322264815-beta-arm64-v8a

**Comment by eyl327** [comment]
My phone (Google Pixel 1) is using the latest beta as well and I do not have this issue.

I have created an export using the Gboard app. You could see if this works.

[LaTeX-Gboard-Dictionary-4.zip](https://github.com/eyl327/LaTeX-Gboard-Dictionary/files/4962279/LaTeX-Gboard-Dictionary-4.zip)

**Comment by eyl327** [comment]
Make sure you are uploading the **zip file** containing the dictionary,txt (and not the txt file by itself)

**Comment by ameybhavsar24** [comment]
> Make sure you are uploading the **zip file** containing the dictionary,txt (and not the txt file by itself)

This worked
